version: "3.8"
services:
  apoe-agent:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
volumes:
  qdrant_data:
