version: '3.8'

services:
  apoe-agent:
    build:
      context: .
    container_name: apoe-agent
    ports:
      - "7000:7000"   # <== This is the port your UI will be on
    env_file:
      - .env          # <== API key here (not committed)
    volumes:
      - ./app:/app

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
